extends:
  - '@meyfa/eslint-config'
  - plugin:react/recommended
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended

plugins:
  - react
  - react-hooks
  - jsx-a11y

parserOptions:
  project: './tsconfig.lint.json'
  ecmaFeatures:
    jsx: true

settings:
  react:
    version: 'detect'

rules:
  react/jsx-pascal-case: ['warn', { allowAllCaps: true, ignore: [] }]
  react/no-typos: ['error']
  react/style-prop-object: ['warn']
  jsx-quotes: ['error', 'prefer-single']
  react/jsx-indent: ['error', 2]
  react/jsx-indent-props: ['error', 2]
  react/jsx-first-prop-new-line: ['error']
  react/jsx-closing-bracket-location: ['error']
  react/jsx-max-props-per-line: ['error', { maximum: 1, when: 'multiline' }]
  react/jsx-props-no-multi-spaces: ['error']
  react/jsx-tag-spacing: ['error']
  react/jsx-equals-spacing: ['error', 'never']
  react/jsx-wrap-multilines: ['warn', { return: 'parens-new-line', arrow: 'parens-new-line' }]
  react/void-dom-elements-no-children: ['error']
  react/no-unstable-nested-components: ['error']
  react/prop-types: ['error', { ignore: ['children'] }]
